WIP: Experience Index Service (XIS) Record status updation
OpenLXP/openlxp-xis pull request #5
Opened 2021-02-25 18:40 UTC by KarenAJ

@OpenLXP/contributors Still adding code to update status of records in XIS.
 However completed validation implementation in code so please do review that.

2021-03-01 16:27 UTC, mattdrayer requested changes

2021-03-01 16:27 UTC, mattdrayer commented on app/api/serializers.py
> +    def validate(self, data):
It seems odd to perform this validation work within the serializers module -- but that could be the DRF design recommendation?

2021-03-01 16:27 UTC, mattdrayer commented on app/api/urls.py
> +]
Need a newline

2021-03-01 16:27 UTC, mattdrayer commented on app/api/views.py
> +        serializer = MetadataLedgerSerializer(record_in_table,
Is this line of code indented properly? If so it looks like there is potential for record_in_table to be null/missing.

2021-03-01 16:27 UTC, mattdrayer commented on app/api/views.py
> +            # If not received send error and bad request status
Since you are specifying a `return` here you can invert the `if` check to create a short-circuit workflow when `is_valid()` is false.  It can help to simplify the code and make for easier test/branch coverage.

2021-03-01 16:27 UTC, mattdrayer commented on app/core/utils/utils.py
> +    bucket_name = 'dauxsr'
At this point the XIS shouldn't have to know anything about DAU -- DAU-specific metadata has been standardized by the XIA into P2881 format.  You may instead need P2881-specific bucket/source/schema info.

2021-03-01 16:27 UTC, mattdrayer commented on docker-compose.yml
> +    external: true
Need a newline

2021-03-01 18:58 UTC, KarenAJ commented on app/api/serializers.py
> +    def validate(self, data):
In the DRF design, the validation takes place in the serializer before data is stored in the models. As we are storing both data that passes and does not pass validation, we don't return an error but instead just update the validation status. Should I make changes to this? Do I need to call it from somewhere else? @mattdrayer

2021-03-01 19:01 UTC, mattdrayer commented on app/api/serializers.py
> +    def validate(self, data):
No, it's fine, I was just wondering.  Makes sense to me.

2021-03-01 19:32 UTC, KarenAJ commented on app/api/views.py
> +        serializer = MetadataLedgerSerializer(record_in_table,
So as we have scope for data that could have older copies in the table that need to be updated to inactive and new data that just has to be created, I've tried to combine the updating and creating steps. If there is a older copy of the record record_in_table would return the value and correspondingly an update would take place else record_in_table return a null value and it just creates a new record in the table.

2021-03-01 19:39 UTC, mattdrayer commented on app/api/views.py
> +        serializer = MetadataLedgerSerializer(record_in_table,
Sure, but my point is that if `key_value` is `None` there will be no `record_in_table`

2021-03-01 19:43 UTC, KarenAJ commented on app/api/views.py
> +        serializer = MetadataLedgerSerializer(record_in_table,
As I've used filter, it does not matter if it's not in the table, the code will continue. And if record_in_table remains None update will not be called while in save method, only create will be called. I initially used a object.get() and that would break the code

2021-03-01 19:58 UTC, mattdrayer commented on app/api/views.py
> +        serializer = MetadataLedgerSerializer(record_in_table,
It's not a question of if the variable's value is None -- the variable will not exist at all, and will essentially raise a NullReferenceError

2021-03-01 20:22 UTC, KarenAJ commented on app/api/views.py
> +        serializer = MetadataLedgerSerializer(record_in_table,
If the value is not in the table filter returns None, and subsequently that value is used for the code. I may be missing something Matt. Hopefully if you could explain it in more detail and maybe I'll get it.

2021-03-01 20:42 UTC, mattdrayer commented on app/api/views.py
> +        serializer = MetadataLedgerSerializer(record_in_table,
You just need to initialize `record_in_table` prior to the `if` statement -- then it will always exist regardless of whether or not `self.instance` is None or `validated_date.get()` returns None.

2021-03-01 21:29 UTC, KarenAJ commented on app/api/views.py
> +        serializer = MetadataLedgerSerializer(record_in_table,
Oh I get it, so for when key_value is null to keep it from an error, I missed that case thanks for this.

2021-03-02 20:44 UTC, mattdrayer approved these changes

2021-03-02 22:57 UTC, SHGODE approved these changes
Approved!

2021-03-02 23:00 UTC, merged