Homoglyphs check
OpenLXP/openlxp-xis pull request #72
Opened 2023-06-13 16:18 UTC by KarenAJ

2023-06-19 13:46 UTC, JDTobin requested changes
remove data_is_safe argument

2023-06-19 13:46 UTC, JDTobin commented on app/core/management/utils/xis_internal.py
> +def confusable_homoglyphs_check(id_num, data, data_is_safe):
Don't have data_is_safe as an argument

2023-06-19 13:46 UTC, JDTobin commented on app/core/management/utils/xis_internal.py
> +            data_is_safe = confusable_homoglyphs_check(id_num, data[key],
check if recursive call returns false, to set data_is_safe to false

2023-06-19 13:46 UTC, JDTobin commented on app/core/management/utils/xis_internal.py
> +            if bool(confusables.is_dangerous(data[key])):
Could combine if statements here

2023-06-19 13:46 UTC, JDTobin commented on app/api/serializers.py
> +        safe_data = confusable_homoglyphs_check(id_num, json_metadata, True)
Don't pass in True

2023-06-19 13:46 UTC, JDTobin commented on app/api/serializers.py
> +        safe_data = confusable_homoglyphs_check(id_num, json_metadata, True)
Don't pass in True

2023-06-19 13:46 UTC, JDTobin requested changes
remove data_is_safe argument

2023-06-19 17:36 UTC, sammy-sandhu approved these changes

2023-06-20 19:35 UTC, JDTobin approved these changes
LGTM

2023-06-21 16:00 UTC, merged